---
abstract: 'Determine Kazakhstan official holidays and business days.'
author:
  - 'Vladimir Varlamov <bes.internal@gmail.com>'
build_requires:
  Module::Build: '0.28'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Date-Holidays-KZ
requires:
  Carp: '0'
  Exporter: '0'
  List::Util: '0'
  Time::Piece: '0'
  base: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  repository: https://github.com/bes-internal/Date-Holidays-KZ.git
version: 0.2019.1
x_generated_by_perl: v5.24.3
x_serialization_backend: 'YAML::Tiny version 1.73'
